// This file is generated by Slice Machine. Update with care!

import CallToAction from './CallToAction';
import Navigation from './Navigation';
import Tools from './Tools';

export {
	CallToAction,
	Navigation,
	Tools,
};

export const components = {
	call_to_action: CallToAction,
	navigation: Navigation,
	tools: Tools,
};
